export const updateData = (data) => ({ type: 'CHANGE_VALUE', data})
export const updateInput = (name, value) => ({ type: 'CHANGE_INPUT', name, value})
export const setCalendarEvents = (data) => ({ type: 'SET_CALENDAR_EVENTS', data})
export const setFormEvent = (data) => ({ type: 'SET_FORM_EVENT', data})
export const setFullBrands = (data) => ({ type: 'SET_FULL_BRANDS', data})
export const setBrands = (data) => ({ type: 'SET_LIST_BRANDS', data})
export const setDomains = (data) => ({ type: 'SET_LIST_DOMAINS', data})
export const setLanguages = (data) => ({ type: 'SET_LIST_LANGUAGES', data})
export const setProducts = (data) => ({ type: 'SET_LIST_PRODUCTS', data})
export const setSegments = (data) => ({ type: 'SET_LIST_SEGMENTS', data})
